"""
Django settings for aditshsoft project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1no&#w^+=ndc94y%ix$$v(zzoq!1^%-crd7rrnjs@mo)_uiff5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_main',
    'hrms_management',
    'hrms_website',
    'knowleage_tranning',
    'hrms_employees',
    'employee_website',
    'rest_framework',
    'rest_framework.authtoken',
    'django_cron',
]
AUTH_USER_MODEL = 'hrms_management.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aditshsoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aditshsoft.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#'NAME': 'dev_aditshsoft_hrms7',

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
       
	    'NAME': 'dev_aditshsoft_hrms',
	    # 'NAME': 'dev_aditshsoft_hrms',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '',
    },
 }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE =  'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True


## Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
# STATIC_URL = '/static/'
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join('/home/aditshsoft/crm_management/robotic-banking-python-backend/aditshsoft', 'media/')
# STATICFILES_DIRS = [
#     "static",
#     "images",
# ]



STATIC_URL = '/static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = MEDIA_URL
STATICFILES_DIRS = [
    "static",
    "images",

]


SUPERUSERLOGINURL = '/admin/'
CRON_CLASSES = [
    "crm_api.attendence_logout_cron.MyCronJob",
    "crm_api.send_push_notification_after_working_days_cron.MyCronJob",
]
FCM_KEY = 'AAAAcHhFvPw:APA91bGFY69B2LkBtp-V0IMSi_K52yS7ru8yj4SwAfzp0vX-yo--GeRZR958qUrxMxhu1-2G2BWGwxRjGlBY885pnUnsSaz6KEzsHl5w7zJxeqsuMOB5bfxqrt__2kXpkdIzUqgGIUQp'
GCM_LINK = 'https://fcm.googleapis.com/fcm/send'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'testing.flexsin@gmail.com'
EMAIL_HOST_PASSWORD = 'Flexsin123!@#'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
SMS_API_KEY = '6679ecik51rc84yvg5vrl4d9yy893f65hgo'
SMS_BASE_URL = 'https://instantalerts.co/api/web/send?apikey='
SMS_SENDER_MOBILE = 'ADITSH'
